name: Apply
on:
  # push:
  #   branches:
  #   - main
  workflow_dispatch:
jobs:
  test_plan:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform Plan
      run: terraform plan -out plan.out
      env:
        TF_VAR_GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
        TF_VAR_GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
        TF_VAR_GITHUB_INSTALL_ENARX: ${{ secrets.GH_APP_INSTALL_ENARX }}
        TF_VAR_GITHUB_INSTALL_PROFIANINC: ${{ secrets.GH_APP_INSTALL_PROFIANINC }}
    - name: Terraform Apply
      run: terraform apply plan.out
      env:
        TF_VAR_GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
        TF_VAR_GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
        TF_VAR_GITHUB_INSTALL_ENARX: ${{ secrets.GH_APP_INSTALL_ENARX }}
        TF_VAR_GITHUB_INSTALL_PROFIANINC: ${{ secrets.GH_APP_INSTALL_PROFIANINC }}
