name: Apply
on:
  push:
    branches:
    - main
  workflow_dispatch:
concurrency:
  group: production
  cancel-in-progress: true
jobs:
  test_plan:
    runs-on: ubuntu-latest
    concurrency: terraform
    permissions:
      contents: read
      id-token: write
    env:
      TF_VAR_GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      TF_VAR_GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      TF_VAR_GITHUB_INSTALL_ENARX: ${{ secrets.GH_APP_INSTALL_ENARX }}
      TF_VAR_GITHUB_INSTALL_PROFIANINC: ${{ secrets.GH_APP_INSTALL_PROFIANINC }}
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -out plan.out
    - name: Terraform Apply
      run: terraform apply plan.out
